apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: {{index . "namespace"}}
spec:
  values:
    defaultRules:
      rules:
        etcd: false
    kubeEtcd:
      enabled: false
    kubeControllerManager:
      enabled: true
      endpoints:
        - {{index . "masterIp"}}
      service:
        enabled: true
        port: 10257
        targetPort: 10257
      serviceMonitor:
        enabled: true
        https: true
        insecureSkipVerify: true
    kubeScheduler:
      enabled: true
      endpoints:
        - {{index . "masterIp"}}
      service:
        enabled: true
        port: 10259
        targetPort: 10259
      serviceMonitor:
        enabled: true
        https: true
        insecureSkipVerify: true
    kubeProxy:
      enabled: true
      endpoints:
        - {{index . "masterIp"}}
      service:
        enabled: true
        port: 10249
        targetPort: 10249
