apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - grafana-secret.yaml
  {{- if index . "isClusterIssuerInstalled" }}
  - certificates.yaml
  {{- end }}
  - release.yaml
